import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import http from 'node:http';
import fs from 'node:fs/promises';
import {createAppServer} from '../server.mjs';
import {LANGUAGES} from '../src/languages.js';
import {translate} from '../src/i18n.js';
const {chromium}=createRequire(import.meta.url)(process.argv[2]||'playwright');
const requests=[];
const provider=http.createServer(async(req,res)=>{
  const chunks=[];for await(const chunk of req)chunks.push(chunk);
  const body=JSON.parse(Buffer.concat(chunks).toString());requests.push(body);
  const result={dish:'Protein',summary:'Fixture food text stays unchanged.',confidence:.88,portion_notes:'100 g',items:[{name:'Protein',quantity:'100 g',grams:100,calories:155,protein_g:13,carbs_g:1,fat_g:11}],total:{calories:155},health_score:70};
  res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(result)}}]}));
});
await new Promise(resolve=>provider.listen(0,'127.0.0.1',resolve));const api=`http://127.0.0.1:${provider.address().port}`;
const app=createAppServer({allowedOrigins:[api]});await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));let browser;
try{
  browser=await chromium.launch({headless:true,...(process.argv[3]?{executablePath:process.argv[3]}:{})});
  const page=await browser.newPage({viewport:{width:1360,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(({api})=>{if(!localStorage.getItem('nutrilens.settings.v1'))localStorage.setItem('nutrilens.settings.v1',JSON.stringify({connectionRevision:2,provider:'custom',baseUrl:api+'/v1',model:'mock',auth:'none',transport:'relay',language:'en'}));},{api});
  await page.goto(`http://127.0.0.1:${app.address().port}`);
  await page.locator('#input').fill('Protein — 100 g');await page.locator('#settings-btn').click();
  assert.equal(await page.locator('#set-language option').count(),11);
  for(const language of LANGUAGES){
    await page.locator('#set-language').selectOption(language.code);
    await page.waitForFunction(code=>document.documentElement.lang===code,language.code);
    assert.equal(await page.locator('html').getAttribute('dir'),language.direction||'ltr');
    assert.equal((await page.locator('#view-analysis').textContent()).trim(),translate('Analyse food',language.code));
    assert.equal((await page.locator('label[for="set-language"]').textContent()).trim(),translate('Language',language.code));
    assert.equal((await page.locator('.hero > p').textContent()).trim(),translate("Attach a photo or describe your meal. NutriLens breaks it down into calories, macros, micronutrients and a health score.",language.code));
    assert.equal(await page.locator('#diary-calories').getAttribute('placeholder'),'123');
    assert.equal(await page.locator('.brand-tag').count(),0);
    assert.equal(await page.title(),'NutriLens');
    assert.equal(await page.locator('#input').inputValue(),'Protein — 100 g');
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('nutrilens.settings.v1')).language),language.code);
  }
  await page.locator('#set-language').selectOption('nb');
  assert.match(await page.locator('#input').getAttribute('placeholder'),/Beskriv maten/);
  await page.locator('#close-drawer').click();
  await page.locator('#send-btn').click();await page.waitForSelector('#result .total-kcal');
  await page.waitForFunction(()=>!document.querySelector('#send-btn').disabled);
  assert.match(requests[0].messages[0].content,/RESPONSE LANGUAGE: Norwegian Bokmål \(nb\)/);
  assert.equal(await page.locator('#result h2').first().textContent(),'Protein');
  assert.match(await page.locator('#result .macros').textContent(),/Karbohydrater/);
  await page.locator('[data-action="log-diary"]').click();await page.locator('#diary-save').click();
  await page.waitForSelector('[data-diary-entry]');
  assert.equal(await page.locator('[data-diary-entry] strong').first().textContent(),'Protein');
  await page.locator('#settings-btn').click();await page.locator('#set-language').selectOption('nn');await page.locator('#close-drawer').click();
  await page.locator('#diary-food').fill('100 g egg');await page.locator('#diary-save').click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-diary-entry]').length===2);
  assert.match(requests[1].messages[0].content,/Norwegian Nynorsk/);assert.match(requests[1].messages[0].content,/not Bokmål/);
  await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'nn');
  await page.locator('#settings-btn').click();assert.equal(await page.locator('#set-language').inputValue(),'nn');
  await page.locator('#set-language').selectOption('nb');
  const leftovers=await page.evaluate(()=>{
    const output=new Set(),walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
    while(walk.nextNode()){const node=walk.currentNode,el=node.parentElement,text=node.nodeValue.trim();if(!text||!/[A-Za-z]{3}/.test(text)||el.closest('[data-i18n-skip],svg,script,style,kbd,code')||el.offsetParent===null)continue;output.add(text);}
    return [...output];
  });
  await fs.writeFile('artifacts/language-visible-text.json',JSON.stringify(leftovers,null,2));
  await page.screenshot({path:'artifacts/language-settings-norwegian.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await page.locator('#set-language').selectOption('hi');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'artifacts/language-settings-hindi-mobile.png',fullPage:true,animations:'disabled'});
  await page.locator('#set-language').selectOption('ur');
  assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
  assert.equal(await page.locator('label[for="set-language"]').textContent(),'زبان');
  assert.equal(await page.locator('#set-baseurl').inputValue(),api+'/v1');
  assert.equal(await page.locator('#set-baseurl').evaluate(element=>getComputedStyle(element).direction),'ltr');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.ok((await page.locator('#drawer').boundingBox()).x<1);
  await page.screenshot({path:'artifacts/language-settings-urdu-mobile.png',fullPage:true,animations:'disabled'});
  await page.locator('#close-drawer').click();
  await page.locator('#view-analysis').click();await page.locator('#input').fill('100 g چاول');await page.locator('#send-btn').click();
  await page.waitForFunction(()=>document.querySelector('#result .total-kcal')?.textContent==='155kcal');
  await page.waitForFunction(()=>!document.querySelector('#send-btn').disabled);
  assert.match(requests[2].messages[0].content,/RESPONSE LANGUAGE: Urdu \(ur\)/);
  assert.equal(await page.locator('#result h2').first().textContent(),'Protein');
  assert.match(await page.locator('#result .macros').textContent(),/کاربوہائیڈریٹس/);
  await page.screenshot({path:'artifacts/language-analysis-urdu-mobile.png',fullPage:true,animations:'disabled'});
  await page.locator('[data-action="log-diary"]').click();await page.locator('#diary-save').click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-diary-entry]').length===3);
  await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'ur');assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
  await page.locator('#view-diary').click();assert.equal(await page.locator('[data-diary-entry]').count(),3);
  await page.locator('#diary-food').fill('100 g روٹی');await page.locator('#diary-save').click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-diary-entry]').length===4);
  assert.match(requests[3].messages[0].content,/RESPONSE LANGUAGE: Urdu/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#settings-btn').click();await page.locator('#set-language').selectOption('en');
  assert.equal(await page.locator('html').getAttribute('dir'),'ltr');
  await page.locator('#set-language').selectOption('ur');await page.setViewportSize({width:1360,height:1000});
  await page.screenshot({path:'artifacts/language-settings-urdu-desktop.png',fullPage:true,animations:'disabled'});
  assert.deepEqual(errors,[]);console.log('PASS: 11 languages, instant interface switching, settings persistence, localized AI instructions in Analysis and Diary, preserved food text, Urdu RTL layout, Urdu Analysis and Diary responses, mobile and desktop layout.');
}finally{await browser?.close();await Promise.all([app,provider].map(server=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections();})));}
