import {URDU_TRANSLATIONS} from './translations-ur.js';
const rows=`
Language|Språk|Język|Sprache|Wika|Langue|Idioma|Språk|Язык|भाषा
Choose the app and AI response language. Saved automatically.|Velg språk for appen og AI-svarene. Lagres automatisk.|Wybierz język aplikacji i odpowiedzi AI. Zapisywany automatycznie.|Sprache für die App und KI-Antworten wählen. Wird automatisch gespeichert.|Piliin ang wika ng app at mga sagot ng AI. Awtomatikong sine-save.|Choisissez la langue de l’application et des réponses IA. Enregistrée automatiquement.|Elige el idioma de la aplicación y las respuestas de IA. Se guarda automáticamente.|Vel språk for appen og KI-svara. Vert lagra automatisk.|Выберите язык приложения и ответов ИИ. Сохраняется автоматически.|ऐप और AI के जवाबों की भाषा चुनें। अपने आप सहेजी जाती है।
Settings|Innstillinger|Ustawienia|Einstellungen|Mga setting|Paramètres|Ajustes|Innstillingar|Настройки|सेटिंग्स
Analyse food|Analyser mat|Analizuj jedzenie|Essen analysieren|Suriin ang pagkain|Analyser un aliment|Analizar alimentos|Analyser mat|Анализ еды|भोजन का विश्लेषण करें
Daily food diary|Daglig matdagbok|Dziennik żywieniowy|Tägliches Ernährungstagebuch|Araw-araw na talaan ng pagkain|Journal alimentaire quotidien|Diario de alimentación|Dagleg matdagbok|Дневник питания|दैनिक भोजन डायरी
Previous analyses & meals|Tidligere analyser og måltider|Poprzednie analizy i posiłki|Frühere Analysen und Mahlzeiten|Mga nakaraang pagsusuri at pagkain|Analyses et repas précédents|Análisis y comidas anteriores|Tidlegare analysar og måltid|Предыдущие анализы и приёмы пищи|पिछले विश्लेषण और भोजन
Choose a diary meal|Velg et dagbokmåltid|Wybierz posiłek z dziennika|Tagebuchmahlzeit wählen|Pumili ng pagkain sa talaan|Choisir un repas du journal|Elegir una comida del diario|Vel eit dagbokmåltid|Выбрать еду из дневника|डायरी से भोजन चुनें
Revisit saved results or analyse a logged food|Se lagrede resultater eller analyser logget mat|Zobacz zapisane wyniki lub analizuj zapisany posiłek|Gespeicherte Ergebnisse ansehen oder erfasste Speisen analysieren|Balikan ang mga resulta o suriin ang naitalang pagkain|Consultez les résultats ou analysez un aliment enregistré|Consulta resultados o analiza una comida registrada|Sjå lagra resultat eller analyser logga mat|Просмотрите результаты или проанализируйте записанную еду|सहेजे गए परिणाम देखें या दर्ज भोजन का विश्लेषण करें
Know exactly what's|Vit akkurat hva som er|Dowiedz się, co jest|Erfahre genau, was|Alamin kung ano ang|Sachez exactement ce qu’il y a|Descubre qué hay|Vit akkurat kva som er|Узнайте, что|जानें कि क्या है
on your plate|på tallerkenen din|na Twoim talerzu|auf deinem Teller liegt|nasa iyong plato|dans votre assiette|en tu plato|på tallerkenen din|на вашей тарелке|आपकी थाली में
Attach a photo or describe your meal. NutriLens breaks it down into calories, macros, micronutrients and a health score.|Legg ved et bilde eller beskriv måltidet. NutriLens analyserer kalorier, makroer, mikronæringsstoffer og helsescore.|Dodaj zdjęcie lub opisz posiłek. NutriLens analizuje kalorie, makroskładniki, mikroskładniki i ocenę zdrowotną.|Foto hinzufügen oder Mahlzeit beschreiben. NutriLens analysiert Kalorien, Makros, Mikronährstoffe und einen Gesundheitsscore.|Maglakip ng larawan o ilarawan ang pagkain. Sinusuri ng NutriLens ang calories, macros, micronutrients at health score.|Ajoutez une photo ou décrivez votre repas. NutriLens analyse les calories, macros, micronutriments et un score santé.|Adjunta una foto o describe tu comida. NutriLens analiza calorías, macros, micronutrientes y una puntuación de salud.|Legg ved eit bilete eller skildre måltidet. NutriLens analyserer kaloriar, makroar, mikronæringsstoff og helseskår.|Добавьте фото или опишите еду. NutriLens рассчитает калории, макро- и микронутриенты и оценку качества питания.|तस्वीर जोड़ें या भोजन का वर्णन करें। NutriLens कैलोरी, मैक्रो, सूक्ष्म पोषक तत्व और स्वास्थ्य स्कोर का अनुमान देता है।
Photo or text|Bilde eller tekst|Zdjęcie lub tekst|Foto oder Text|Larawan o teksto|Photo ou texte|Foto o texto|Bilete eller tekst|Фото или текст|तस्वीर या टेक्स्ट
Bring your own API|Bruk din egen API|Użyj własnego API|Eigene API verwenden|Gamitin ang sariling API|Utilisez votre API|Usa tu propia API|Bruk din eigen API|Используйте свой API|अपना API इस्तेमाल करें
Macros & micros|Makroer og mikroer|Makro- i mikroskładniki|Makros und Mikros|Macros at micros|Macros et micros|Macros y micros|Makroar og mikroar|Макро- и микронутриенты|मैक्रो और सूक्ष्म पोषक तत्व
Export & print|Eksporter og skriv ut|Eksportuj i drukuj|Exportieren und drucken|I-export at i-print|Exporter et imprimer|Exportar e imprimir|Eksporter og skriv ut|Экспорт и печать|निर्यात और प्रिंट
Photo|Bilde|Zdjęcie|Foto|Larawan|Photo|Foto|Bilete|Фото|तस्वीर
Attach files|Legg ved filer|Dodaj pliki|Dateien anhängen|Maglakip ng mga file|Joindre des fichiers|Adjuntar archivos|Legg ved filer|Прикрепить файлы|फ़ाइलें जोड़ें
Analyse|Analyser|Analizuj|Analysieren|Suriin|Analyser|Analizar|Analyser|Анализировать|विश्लेषण करें
Analysing…|Analyserer…|Analizowanie…|Analyse läuft…|Sinusuri…|Analyse en cours…|Analizando…|Analyserer…|Анализ…|विश्लेषण हो रहा है…
Cancel|Avbryt|Anuluj|Abbrechen|Kanselahin|Annuler|Cancelar|Avbryt|Отмена|रद्द करें
Food description|Matbeskrivelse|Opis jedzenia|Beschreibung des Essens|Paglalarawan ng pagkain|Description de l’aliment|Descripción del alimento|Matskildring|Описание еды|भोजन का विवरण
Describe your food… e.g. “two slices of pepperoni pizza and a coke”, or attach a photo or recipe file.|Beskriv maten… f.eks. «to pizzastykker og en cola», eller legg ved et bilde eller en oppskrift.|Opisz jedzenie… np. „dwa kawałki pizzy i cola”, lub dodaj zdjęcie albo przepis.|Beschreibe dein Essen… z. B. „zwei Stücke Pizza und eine Cola“, oder füge ein Foto oder Rezept hinzu.|Ilarawan ang pagkain… hal. “dalawang hiwa ng pizza at coke”, o maglakip ng larawan o recipe.|Décrivez votre repas… par ex. « deux parts de pizza et un coca », ou joignez une photo ou une recette.|Describe tu comida… p. ej. «dos porciones de pizza y una cola», o adjunta una foto o receta.|Skildre maten… t.d. «to pizzastykke og ein cola», eller legg ved eit bilete eller ei oppskrift.|Опишите еду… например «два куска пиццы и кола», или прикрепите фото или рецепт.|भोजन बताएं… जैसे “पिज़्ज़ा के दो टुकड़े और कोला”, या तस्वीर या रेसिपी जोड़ें।
Try:|Prøv:|Wypróbuj:|Probier:|Subukan:|Essayez :|Prueba:|Prøv:|Попробуйте:|आज़माएं:
Chicken & rice|Kylling og ris|Kurczak i ryż|Hähnchen und Reis|Manok at kanin|Poulet et riz|Pollo y arroz|Kylling og ris|Курица и рис|चिकन और चावल
Latte & muffin|Latte og muffins|Latte i muffinka|Latte und Muffin|Latte at muffin|Latte et muffin|Latte y magdalena|Latte og muffins|Латте и маффин|लाटे और मफ़िन
Pizza & coke|Pizza og cola|Pizza i cola|Pizza und Cola|Pizza at coke|Pizza et coca|Pizza y cola|Pizza og cola|Пицца и кола|पिज़्ज़ा और कोला
Salmon sushi|Laksesushi|Sushi z łososiem|Lachs-Sushi|Salmon sushi|Sushi au saumon|Sushi de salmón|Laksesushi|Суши с лососем|सैल्मन सुशी
A little clarity, every day|Litt mer oversikt, hver dag|Trochę jasności każdego dnia|Jeden Tag etwas mehr Klarheit|Mas malinaw, araw-araw|Un peu de clarté chaque jour|Un poco de claridad cada día|Litt meir oversikt, kvar dag|Больше ясности каждый день|हर दिन थोड़ी और स्पष्टता
Log what you eat. Every entry adds to your daily calorie total.|Logg det du spiser. Hver oppføring legges til dagens kalorier.|Zapisuj, co jesz. Każdy wpis zwiększa dzienną sumę kalorii.|Erfasse, was du isst. Jeder Eintrag zählt zur täglichen Kaloriensumme.|Itala ang kinakain. Bawat tala ay nadaragdag sa calories mo sa araw.|Notez ce que vous mangez. Chaque entrée s’ajoute aux calories du jour.|Registra lo que comes. Cada entrada se suma a las calorías del día.|Logg det du et. Kvar oppføring vert lagd til kaloriane for dagen.|Записывайте еду. Каждая запись добавляется к калориям за день.|आप जो खाते हैं, दर्ज करें। हर प्रविष्टि दैनिक कैलोरी में जुड़ती है।
Today|I dag|Dzisiaj|Heute|Ngayon|Aujourd’hui|Hoy|I dag|Сегодня|आज
today|i dag|dzisiaj|heute|ngayon|aujourd’hui|hoy|i dag|сегодня|आज
Today’s food diary|Dagens matdagbok|Dzisiejszy dziennik|Heutiges Ernährungstagebuch|Talaan ng pagkain ngayon|Journal alimentaire du jour|Diario de hoy|Matdagboka for dagen|Дневник питания за сегодня|आज की भोजन डायरी
Total calories consumed|Totalt inntak av kalorier|Łączna liczba spożytych kalorii|Insgesamt verzehrte Kalorien|Kabuuang calories na nakain|Total des calories consommées|Calorías totales consumidas|Samla kaloriinntak|Всего потреблено калорий|कुल खपत कैलोरी
entry logged|oppføring logget|wpis zapisany|Eintrag erfasst|tala ang naitala|entrée enregistrée|entrada registrada|oppføring logga|запись добавлена|प्रविष्टि दर्ज
entries logged|oppføringer logget|wpisów zapisanych|Einträge erfasst|tala ang naitala|entrées enregistrées|entradas registradas|oppføringar logga|записей добавлено|प्रविष्टियां दर्ज
Breakfast|Frokost|Śniadanie|Frühstück|Almusal|Petit-déjeuner|Desayuno|Frukost|Завтрак|नाश्ता
Lunch|Lunsj|Obiad|Mittagessen|Tanghalian|Déjeuner|Almuerzo|Lunsj|Обед|दोपहर का भोजन
Dinner|Middag|Kolacja|Abendessen|Hapunan|Dîner|Cena|Middag|Ужин|रात का भोजन
Snacks|Mellommåltider|Przekąski|Snacks|Meryenda|Collations|Tentempiés|Mellommåltid|Перекусы|हल्का नाश्ता
Other|Annet|Inne|Sonstiges|Iba pa|Autre|Otro|Anna|Другое|अन्य
Add food or calories|Legg til mat eller kalorier|Dodaj jedzenie lub kalorie|Essen oder Kalorien hinzufügen|Magdagdag ng pagkain o calories|Ajouter un aliment ou des calories|Añadir comida o calorías|Legg til mat eller kaloriar|Добавить еду или калории|भोजन या कैलोरी जोड़ें
Describe your food and leave calories blank for an AI estimate. Enter calories yourself to skip AI.|Beskriv maten og la kalorifeltet stå tomt for et AI-estimat. Skriv inn kalorier selv for å hoppe over AI.|Opisz jedzenie i pozostaw kalorie puste, aby uzyskać szacunek AI. Wpisz kalorie ręcznie, aby pominąć AI.|Beschreibe das Essen und lasse Kalorien für eine KI-Schätzung leer. Trage Kalorien selbst ein, um KI zu überspringen.|Ilarawan ang pagkain at iwang blangko ang calories para sa AI estimate. Ilagay ang calories para laktawan ang AI.|Décrivez l’aliment et laissez les calories vides pour une estimation IA. Saisissez-les pour ignorer l’IA.|Describe la comida y deja las calorías vacías para una estimación de IA. Introdúcelas para omitir la IA.|Skildre maten og la kalorifeltet stå tomt for eit KI-estimat. Skriv inn kaloriar sjølv for å hoppe over KI.|Опишите еду и оставьте калории пустыми для оценки ИИ. Введите калории вручную, чтобы не использовать ИИ.|भोजन बताएं और AI अनुमान के लिए कैलोरी खाली छोड़ें। AI छोड़ने के लिए कैलोरी स्वयं भरें।
Food / meal|Mat / måltid|Jedzenie / posiłek|Essen / Mahlzeit|Pagkain|Aliment / repas|Alimento / comida|Mat / måltid|Еда / приём пищи|खाद्य / भोजन
(optional)|(valgfritt)|(opcjonalnie)|(optional)|(opsyonal)|(facultatif)|(opcional)|(valfritt)|(необязательно)|(वैकल्पिक)
Calories eaten (kcal)|Kalorier spist (kcal)|Spożyte kalorie (kcal)|Verzehrte Kalorien (kcal)|Calories na nakain (kcal)|Calories consommées (kcal)|Calorías consumidas (kcal)|Kaloriar etne (kcal)|Потреблённые калории (ккал)|खाई गई कैलोरी (kcal)
Meal category|Måltidskategori|Kategoria posiłku|Mahlzeitenkategorie|Uri ng pagkain|Type de repas|Tipo de comida|Måltidskategori|Тип приёма пищи|भोजन की श्रेणी
Add entry|Legg til oppføring|Dodaj wpis|Eintrag hinzufügen|Magdagdag ng tala|Ajouter une entrée|Añadir entrada|Legg til oppføring|Добавить запись|प्रविष्टि जोड़ें
Save changes|Lagre endringer|Zapisz zmiany|Änderungen speichern|I-save ang pagbabago|Enregistrer les modifications|Guardar cambios|Lagre endringar|Сохранить изменения|बदलाव सहेजें
Analyse a food instead|Analyser mat i stedet|Zamiast tego analizuj jedzenie|Stattdessen Essen analysieren|Suriin na lang ang pagkain|Analyser plutôt un aliment|Analizar un alimento|Analyser mat i staden|Вместо этого анализировать еду|इसके बजाय भोजन का विश्लेषण करें
Foods eaten|Mat spist|Zjedzone posiłki|Verzehrte Speisen|Mga nakain|Aliments consommés|Alimentos consumidos|Mat eten|Съеденная еда|खाए गए भोजन
Clear this day|Tøm denne dagen|Wyczyść ten dzień|Diesen Tag leeren|Burahin ang araw na ito|Effacer cette journée|Borrar este día|Tøm denne dagen|Очистить этот день|इस दिन को साफ़ करें
AI estimate|AI-estimat|Szacunek AI|KI-Schätzung|AI estimate|Estimation IA|Estimación de IA|KI-estimat|Оценка ИИ|AI अनुमान
Manual entry|Manuell oppføring|Wpis ręczny|Manueller Eintrag|Manwal na tala|Entrée manuelle|Entrada manual|Manuell oppføring|Ручная запись|मैन्युअल प्रविष्टि
Estimated portion|Estimert porsjon|Szacowana porcja|Geschätzte Portion|Tinatayang dami|Portion estimée|Porción estimada|Estimert porsjon|Оценка порции|अनुमानित मात्रा
Detailed nutrition|Detaljert næringsinnhold|Szczegóły wartości odżywczych|Nährwerte im Detail|Detalye ng nutrisyon|Détails nutritionnels|Detalles nutricionales|Detaljert næringsinnhald|Подробные питательные данные|पोषण विवरण
No foods logged for this day|Ingen mat logget denne dagen|Brak posiłków w tym dniu|Für diesen Tag ist kein Essen erfasst|Walang pagkain naitala sa araw na ito|Aucun aliment enregistré ce jour|No hay alimentos registrados este día|Ingen mat logga denne dagen|За этот день еда не записана|इस दिन कोई भोजन दर्ज नहीं है
Cancel estimate|Avbryt estimat|Anuluj szacowanie|Schätzung abbrechen|Kanselahin ang estimate|Annuler l’estimation|Cancelar estimación|Avbryt estimat|Отменить оценку|अनुमान रद्द करें
Estimating calories…|Estimerer kalorier…|Szacowanie kalorii…|Kalorien werden geschätzt…|Tinataya ang calories…|Estimation des calories…|Estimando calorías…|Estimerer kaloriar…|Оценка калорий…|कैलोरी का अनुमान लगाया जा रहा है…
Estimating…|Estimerer…|Szacowanie…|Schätzung läuft…|Tinataya…|Estimation…|Estimando…|Estimerer…|Оценка…|अनुमान लगाया जा रहा है…
Saving…|Lagrer…|Zapisywanie…|Speichern…|Sine-save…|Enregistrement…|Guardando…|Lagrar…|Сохранение…|सहेजा जा रहा है…
Protein|Protein|Białko|Eiweiß|Protina|Protéines|Proteína|Protein|Белки|प्रोटीन
Carbs|Karbohydrater|Węglowodany|Kohlenhydrate|Carbs|Glucides|Carbohidratos|Karbohydrat|Углеводы|कार्बोहाइड्रेट
Fat|Fett|Tłuszcz|Fett|Taba|Lipides|Grasa|Feitt|Жиры|वसा
Fiber|Fiber|Błonnik|Ballaststoffe|Hibla|Fibres|Fibra|Fiber|Клетчатка|फ़ाइबर
Fibre|Fiber|Błonnik|Ballaststoffe|Hibla|Fibres|Fibra|Fiber|Клетчатка|फ़ाइबर
Sugar|Sukker|Cukier|Zucker|Asukal|Sucres|Azúcar|Sukker|Сахар|चीनी
Sodium|Natrium|Sód|Natrium|Sodium|Sodium|Sodio|Natrium|Натрий|सोडियम
AI confidence|AI-sikkerhet|Pewność AI|KI-Konfidenz|Kumpiyansa ng AI|Confiance IA|Confianza de IA|KI-visse|Уверенность ИИ|AI का विश्वास
item|matvare|składnik|Zutat|pagkain|aliment|alimento|matvare|продукт|खाद्य
items|matvarer|składniki|Zutaten|pagkain|aliments|alimentos|matvarer|продукты|खाद्य
Macro split|Fordeling av makroer|Podział makroskładników|Makroverteilung|Hatian ng macros|Répartition des macros|Distribución de macros|Fordeling av makroar|Распределение макронутриентов|मैक्रो का वितरण
Micronutrients|Mikronæringsstoffer|Mikroskładniki|Mikronährstoffe|Micronutrients|Micronutriments|Micronutrientes|Mikronæringsstoff|Микронутриенты|सूक्ष्म पोषक तत्व
Breakdown|Fordeling|Szczegóły|Aufschlüsselung|Detalye|Détail|Desglose|Fordeling|Разбивка|विवरण
ITEM|MATVARE|SKŁADNIK|ZUTAT|PAGKAIN|ALIMENT|ALIMENTO|MATVARE|ПРОДУКТ|खाद्य
PORTION|PORSJON|PORCJA|PORTION|DAMI|PORTION|PORCIÓN|PORSJON|ПОРЦИЯ|मात्रा
Smart swaps|Smarte alternativer|Zdrowsze zamienniki|Cleverer Austausch|Mas mabuting kapalit|Alternatives futées|Alternativas saludables|Smarte alternativ|Полезные замены|बेहतर विकल्प
Analyse again|Analyser igjen|Analizuj ponownie|Erneut analysieren|Suriin muli|Analyser à nouveau|Analizar de nuevo|Analyser på nytt|Анализировать снова|फिर विश्लेषण करें
Log to diary|Logg i dagboken|Zapisz w dzienniku|Im Tagebuch erfassen|Itala sa diary|Ajouter au journal|Registrar en el diario|Logg i dagboka|Записать в дневник|डायरी में दर्ज करें
Copy summary|Kopier sammendrag|Kopiuj podsumowanie|Zusammenfassung kopieren|Kopyahin ang buod|Copier le résumé|Copiar resumen|Kopier samandrag|Копировать итог|सारांश कॉपी करें
Print|Skriv ut|Drukuj|Drucken|I-print|Imprimer|Imprimir|Skriv ut|Печать|प्रिंट
Analysis failed|Analysen mislyktes|Analiza nie powiodła się|Analyse fehlgeschlagen|Nabigo ang pagsusuri|Échec de l’analyse|Error en el análisis|Analysen mislukkast|Ошибка анализа|विश्लेषण विफल
Retry|Prøv igjen|Spróbuj ponownie|Erneut versuchen|Subukang muli|Réessayer|Reintentar|Prøv på nytt|Повторить|फिर प्रयास करें
Open settings|Åpne innstillinger|Otwórz ustawienia|Einstellungen öffnen|Buksan ang settings|Ouvrir les paramètres|Abrir ajustes|Opne innstillingar|Открыть настройки|सेटिंग्स खोलें
Previous analyses|Tidligere analyser|Poprzednie analizy|Frühere Analysen|Mga nakaraang pagsusuri|Analyses précédentes|Análisis anteriores|Tidlegare analysar|Предыдущие анализы|पिछले विश्लेषण
Diary meals|Dagbokmåltider|Posiłki z dziennika|Tagebuchmahlzeiten|Mga pagkain sa diary|Repas du journal|Comidas del diario|Dagbokmåltid|Еда из дневника|डायरी के भोजन
Your nutrition library|Ditt næringsbibliotek|Twoja biblioteka żywieniowa|Deine Ernährungsbibliothek|Iyong talaan ng nutrisyon|Votre bibliothèque nutritionnelle|Tu biblioteca de nutrición|Næringsbiblioteket ditt|Ваша библиотека питания|आपकी पोषण लाइब्रेरी
Meals & analyses|Måltider og analyser|Posiłki i analizy|Mahlzeiten und Analysen|Mga pagkain at pagsusuri|Repas et analyses|Comidas y análisis|Måltid og analysar|Еда и анализы|भोजन और विश्लेषण
Search meals|Søk etter måltider|Szukaj posiłków|Mahlzeiten suchen|Maghanap ng pagkain|Rechercher des repas|Buscar comidas|Søk etter måltid|Поиск еды|भोजन खोजें
Search previous analyses…|Søk i tidligere analyser…|Szukaj poprzednich analiz…|Frühere Analysen suchen…|Hanapin ang nakaraang pagsusuri…|Rechercher des analyses…|Buscar análisis anteriores…|Søk i tidlegare analysar…|Поиск предыдущих анализов…|पिछले विश्लेषण खोजें…
Search diary meals…|Søk i dagbokmåltider…|Szukaj posiłków z dziennika…|Tagebuchmahlzeiten suchen…|Hanapin ang pagkain sa diary…|Rechercher des repas du journal…|Buscar comidas del diario…|Søk i dagbokmåltid…|Поиск еды в дневнике…|डायरी के भोजन खोजें…
Show more meals|Vis flere måltider|Pokaż więcej posiłków|Weitere Mahlzeiten anzeigen|Ipakita pa ang pagkain|Afficher plus de repas|Mostrar más comidas|Vis fleire måltid|Показать больше еды|और भोजन दिखाएं
Delete all analyses|Slett alle analyser|Usuń wszystkie analizy|Alle Analysen löschen|Burahin ang lahat ng pagsusuri|Supprimer toutes les analyses|Eliminar todos los análisis|Slett alle analysar|Удалить все анализы|सभी विश्लेषण मिटाएं
Delete all diary meals|Slett alle dagbokmåltider|Usuń wszystkie posiłki z dziennika|Alle Tagebuchmahlzeiten löschen|Burahin lahat ng pagkain sa diary|Supprimer tous les repas du journal|Eliminar todas las comidas del diario|Slett alle dagbokmåltid|Удалить всю еду из дневника|डायरी के सभी भोजन मिटाएं
Download history backup|Last ned sikkerhetskopi|Pobierz kopię historii|Verlaufssicherung herunterladen|I-download ang backup|Télécharger une sauvegarde|Descargar copia de seguridad|Last ned tryggleikskopi|Скачать резервную копию|इतिहास का बैकअप डाउनलोड करें
Restore backup|Gjenopprett sikkerhetskopi|Przywróć kopię|Sicherung wiederherstellen|Ibalik ang backup|Restaurer une sauvegarde|Restaurar copia|Gjenopprett tryggleikskopi|Восстановить копию|बैकअप बहाल करें
Provider preset|Leverandørvalg|Dostawca API|Anbietervorlage|Napiling provider|Préréglage du fournisseur|Proveedor predefinido|Leverandørval|Выбор провайдера|प्रदाता का विकल्प
API base URL|API-baseadresse|Adres bazowy API|API-Basis-URL|Base URL ng API|URL de base de l’API|URL base de la API|API-baseadresse|Базовый URL API|API का बेस URL
API format|API-format|Format API|API-Format|Format ng API|Format de l’API|Formato de API|API-format|Формат API|API फ़ॉर्मैट
Connection method|Tilkoblingsmetode|Metoda połączenia|Verbindungsmethode|Paraan ng koneksyon|Mode de connexion|Método de conexión|Tilkoplingsmetode|Способ подключения|कनेक्शन का तरीका
Model|Modell|Model|Modell|Modelo|Modèle|Modelo|Modell|Модель|मॉडल
Fetch available models|Hent tilgjengelige modeller|Pobierz dostępne modele|Verfügbare Modelle abrufen|Kunin ang mga modelo|Charger les modèles disponibles|Obtener modelos disponibles|Hent tilgjengelege modellar|Загрузить доступные модели|उपलब्ध मॉडल लाएं
API key|API-nøkkel|Klucz API|API-Schlüssel|API key|Clé API|Clave API|API-nøkkel|Ключ API|API कुंजी
Authentication style|Autentiseringstype|Typ uwierzytelniania|Authentifizierungsart|Uri ng authentication|Mode d’authentification|Tipo de autenticación|Autentiseringstype|Тип аутентификации|प्रमाणीकरण का प्रकार
No key|Ingen nøkkel|Bez klucza|Kein Schlüssel|Walang key|Sans clé|Sin clave|Ingen nøkkel|Без ключа|बिना कुंजी
Advanced request options|Avanserte forespørselsvalg|Zaawansowane opcje żądania|Erweiterte Anfrageoptionen|Advanced na opsyon|Options avancées|Opciones avanzadas|Avanserte førespurnadsval|Расширенные параметры запроса|उन्नत अनुरोध विकल्प
Custom auth header name|Egendefinert autentiseringsheader|Nazwa nagłówka uwierzytelniania|Eigener Authentifizierungsheader|Pangalan ng auth header|Nom d’en-tête personnalisé|Nombre de cabecera de autenticación|Eigendefinert autentiseringsheader|Имя заголовка аутентификации|कस्टम प्रमाणीकरण हेडर
Temperature|Temperatur|Temperatura|Temperatur|Temperature|Température|Temperatura|Temperatur|Температура|तापमान
Max output tokens|Maks utdata-tokens|Maksymalna liczba tokenów|Maximale Ausgabetokens|Pinakamaraming output tokens|Nombre maximal de tokens|Máximo de tokens de salida|Maks utdata-token|Максимум токенов ответа|अधिकतम आउटपुट टोकन
Appearance|Utseende|Wygląd|Darstellung|Hitsura|Apparence|Apariencia|Utsjånad|Оформление|दिखावट
Dark|Mørk|Ciemny|Dunkel|Madilim|Sombre|Oscuro|Mørk|Тёмная|डार्क
Light|Lys|Jasny|Hell|Maliwanag|Clair|Claro|Lys|Светлая|लाइट
Preferences|Preferanser|Preferencje|Voreinstellungen|Mga kagustuhan|Préférences|Preferencias|Preferansar|Предпочтения|प्राथमिकताएं
Demo mode (sample data only)|Demomodus (kun eksempeldata)|Tryb demo (tylko dane przykładowe)|Demomodus (nur Beispieldaten)|Demo mode (halimbawang data lang)|Mode démo (exemples uniquement)|Modo demo (solo ejemplos)|Demomodus (berre dømedata)|Демо-режим (только примеры)|डेमो मोड (केवल नमूना डेटा)
Show micronutrients|Vis mikronæringsstoffer|Pokaż mikroskładniki|Mikronährstoffe anzeigen|Ipakita ang micronutrients|Afficher les micronutriments|Mostrar micronutrientes|Vis mikronæringsstoff|Показывать микронутриенты|सूक्ष्म पोषक तत्व दिखाएं
Show item breakdown|Vis matvarefordeling|Pokaż podział składników|Zutatenübersicht anzeigen|Ipakita ang detalye|Afficher le détail des aliments|Mostrar desglose de alimentos|Vis matvarefordeling|Показывать состав|खाद्य विवरण दिखाएं
Show smart swaps|Vis smarte alternativer|Pokaż zdrowsze zamienniki|Clevere Alternativen anzeigen|Ipakita ang mas mabuting kapalit|Afficher les alternatives|Mostrar alternativas saludables|Vis smarte alternativ|Показывать полезные замены|बेहतर विकल्प दिखाएं
Test connection|Test tilkobling|Testuj połączenie|Verbindung testen|Subukan ang koneksyon|Tester la connexion|Probar conexión|Test tilkopling|Проверить подключение|कनेक्शन जांचें
Reset settings|Tilbakestill innstillinger|Zresetuj ustawienia|Einstellungen zurücksetzen|I-reset ang settings|Réinitialiser les paramètres|Restablecer ajustes|Nullstill innstillingar|Сбросить настройки|सेटिंग्स रीसेट करें
Analysing your recipe attachments…|Analyserer oppskriftsvedleggene…|Analizowanie załączonych przepisów…|Rezeptdateien werden analysiert…|Sinusuri ang mga recipe…|Analyse des recettes jointes…|Analizando recetas adjuntas…|Analyserer oppskriftsvedlegga…|Анализ приложенных рецептов…|जुड़ी रेसिपी का विश्लेषण हो रहा है…
Analysing your photo…|Analyserer bildet ditt…|Analizowanie zdjęcia…|Foto wird analysiert…|Sinusuri ang larawan…|Analyse de votre photo…|Analizando tu foto…|Analyserer biletet ditt…|Анализ фото…|आपकी तस्वीर का विश्लेषण हो रहा है…
Analysing your description…|Analyserer beskrivelsen…|Analizowanie opisu…|Beschreibung wird analysiert…|Sinusuri ang paglalarawan…|Analyse de votre description…|Analizando tu descripción…|Analyserer skildringa…|Анализ описания…|आपके विवरण का विश्लेषण हो रहा है…
Repairing the nutrition response…|Retter næringssvaret…|Poprawianie odpowiedzi…|Nährwertantwort wird korrigiert…|Inaayos ang sagot…|Correction de la réponse…|Corrigiendo la respuesta…|Rettar næringssvaret…|Исправление ответа…|पोषण का जवाब सुधारा जा रहा है…
`;
const codes=['nb','pl','de','tl','fr','es','nn','ru','hi'];
export const TRANSLATIONS=Object.fromEntries(codes.map(code=>[code,{}]));
for(const line of rows.trim().split('\n')){
  const [english,...values]=line.split('|');
  if(values.length!==codes.length)throw new Error('Incomplete translation: '+english);
  codes.forEach((code,index)=>TRANSLATIONS[code][english]=values[index]);
}
const moreRows=`
Attach a photo, add a recipe file, or describe a meal, then hit|Legg ved et bilde eller en oppskrift, eller beskriv maten og trykk|Dodaj zdjęcie lub przepis albo opisz posiłek i naciśnij|Foto oder Rezept hinzufügen oder Essen beschreiben, dann auf|Maglakip ng larawan o recipe, o ilarawan ang pagkain, at pindutin|Ajoutez une photo ou une recette, ou décrivez le repas, puis cliquez sur|Adjunta una foto o receta, o describe la comida, y pulsa|Legg ved eit bilete eller ei oppskrift, eller skildre maten og trykk|Добавьте фото или рецепт, или опишите еду и нажмите|तस्वीर या रेसिपी जोड़ें, या भोजन बताएं, फिर दबाएं
Results appear here with calories, macros, micronutrients and a health score.|Her vises kalorier, makroer, mikronæringsstoffer og helsescore.|Tutaj pojawią się kalorie, makroskładniki, mikroskładniki i ocena.|Hier erscheinen Kalorien, Makros, Mikronährstoffe und Gesundheitsscore.|Dito lalabas ang calories, macros, micronutrients at health score.|Les calories, macros, micronutriments et le score santé apparaîtront ici.|Aquí verás calorías, macros, micronutrientes y puntuación de salud.|Her vert kaloriar, makroar, mikronæringsstoff og helseskår viste.|Здесь появятся калории, нутриенты и оценка качества питания.|यहां कैलोरी, मैक्रो, सूक्ष्म पोषक तत्व और स्वास्थ्य स्कोर दिखेंगे।
Ready to use your configured model. Press Analyse to send the request.|Modellen er klar. Trykk Analyser for å sende forespørselen.|Model jest gotowy. Naciśnij Analizuj, aby wysłać żądanie.|Modell bereit. Klicke auf Analysieren, um die Anfrage zu senden.|Handa na ang modelo. Pindutin ang Suriin para ipadala.|Le modèle est prêt. Cliquez sur Analyser pour envoyer la demande.|Modelo listo. Pulsa Analizar para enviar la solicitud.|Modellen er klar. Trykk Analyser for å sende førespurnaden.|Модель готова. Нажмите «Анализировать».|मॉडल तैयार है। अनुरोध भेजने के लिए विश्लेषण करें दबाएं।
Open Settings, add your API key and fetch/select a model. No demo results are substituted.|Åpne Innstillinger, legg til API-nøkkel og velg modell. Ingen demodata brukes.|Otwórz Ustawienia, dodaj klucz API i wybierz model. Dane demo nie są używane.|Einstellungen öffnen, API-Schlüssel hinzufügen und Modell wählen. Keine Demo-Ergebnisse.|Buksan ang settings, ilagay ang API key at pumili ng modelo. Walang demo na ipapalit.|Ouvrez les paramètres, ajoutez votre clé API et choisissez un modèle. Aucun résultat démo substitué.|Abre Ajustes, añade tu clave API y elige un modelo. No se usan resultados demo.|Opne Innstillingar, legg til API-nøkkel og vel modell. Ingen demodata vert brukte.|Откройте настройки, добавьте ключ API и выберите модель. Демо-данные не подставляются.|सेटिंग्स खोलें, API कुंजी जोड़ें और मॉडल चुनें। डेमो परिणाम इस्तेमाल नहीं होंगे।
to analyse ·|for å analysere ·|aby analizować ·|zum Analysieren ·|para suriin ·|pour analyser ·|para analizar ·|for å analysere ·|для анализа ·|विश्लेषण के लिए ·
for a new line|for en ny linje|aby dodać nowy wiersz|für eine neue Zeile|para sa bagong linya|pour une nouvelle ligne|para una nueva línea|for ei ny linje|для новой строки|नई पंक्ति के लिए
for a new line.|for en ny linje.|aby dodać nowy wiersz.|für eine neue Zeile.|para sa bagong linya.|pour une nouvelle ligne.|para una nueva línea.|for ei ny linje.|для новой строки.|नई पंक्ति के लिए।
Recipes: PDF, DOCX, TXT, Markdown, CSV or JSON|Oppskrifter: PDF, DOCX, TXT, Markdown, CSV eller JSON|Przepisy: PDF, DOCX, TXT, Markdown, CSV lub JSON|Rezepte: PDF, DOCX, TXT, Markdown, CSV oder JSON|Recipe: PDF, DOCX, TXT, Markdown, CSV o JSON|Recettes : PDF, DOCX, TXT, Markdown, CSV ou JSON|Recetas: PDF, DOCX, TXT, Markdown, CSV o JSON|Oppskrifter: PDF, DOCX, TXT, Markdown, CSV eller JSON|Рецепты: PDF, DOCX, TXT, Markdown, CSV или JSON|रेसिपी: PDF, DOCX, TXT, Markdown, CSV या JSON
up to 5 files, 5 MB each|opptil 5 filer, 5 MB hver|do 5 plików, po 5 MB|bis zu 5 Dateien, je 5 MB|hanggang 5 file, tig-5 MB|jusqu’à 5 fichiers de 5 Mo|hasta 5 archivos de 5 MB|opptil 5 filer, 5 MB kvar|до 5 файлов, по 5 МБ|अधिकतम 5 फ़ाइलें, हर फ़ाइल 5 MB
Your key is stored in this browser. The optional local relay forwards requests only to your chosen endpoint and never logs or saves keys.|Nøkkelen lagres i denne nettleseren. Lokal videresending sender kun til valgt endepunkt og lagrer aldri nøkler.|Klucz jest zapisany w przeglądarce. Lokalny przekaźnik wysyła tylko do wybranego endpointu i nie zapisuje kluczy.|Dein Schlüssel bleibt im Browser. Der lokale Relay sendet nur an deinen Endpunkt und speichert keine Schlüssel.|Naka-save ang key sa browser. Sa napiling endpoint lang nagpapadala ang lokal na relay; hindi nito sine-save ang mga key.|Votre clé reste dans ce navigateur. Le relais local transmet uniquement au point choisi, sans enregistrer les clés.|Tu clave se guarda en este navegador. El relay local solo envía al destino elegido y nunca guarda claves.|Nøkkelen vert lagra i denne nettlesaren. Lokal vidaresending sender berre til valt endepunkt og lagrar aldri nøklar.|Ключ хранится в браузере. Локальный ретранслятор отправляет запросы только выбранному провайдеру и не сохраняет ключи.|कुंजी इस ब्राउज़र में सहेजी जाती है। स्थानीय रिले केवल चुने एंडपॉइंट को अनुरोध भेजता है और कुंजी सहेजता नहीं है।
Estimates are for general information and are not medical or dietary advice.|Estimatene er generell informasjon, ikke medisinske råd eller kostholdsråd.|Szacunki służą informacji, nie są poradą medyczną ani dietetyczną.|Schätzungen dienen der Information, nicht als medizinische oder Ernährungsberatung.|Impormasyon lang ang mga estimate, hindi payong medikal o pandiyeta.|Les estimations sont informatives, pas des conseils médicaux ou diététiques.|Las estimaciones son informativas, no consejos médicos o dietéticos.|Estimata er generell informasjon, ikkje medisinske råd eller kosthaldsråd.|Оценки носят информационный характер и не являются медицинскими советами.|अनुमान सामान्य जानकारी के लिए हैं, चिकित्सा या आहार संबंधी सलाह नहीं।
Pick a known provider or “Custom” for any OpenAI-compatible API.|Velg en leverandør eller «Egendefinert» for en OpenAI-kompatibel API.|Wybierz dostawcę lub „Niestandardowy” dla API zgodnego z OpenAI.|Anbieter oder „Benutzerdefiniert“ für OpenAI-kompatible APIs wählen.|Pumili ng provider o “Custom” para sa OpenAI-compatible na API.|Choisissez un fournisseur ou « Personnalisé » pour une API compatible OpenAI.|Elige un proveedor o «Personalizado» para una API compatible con OpenAI.|Vel ein leverandør eller «Eigendefinert» for ein OpenAI-kompatibel API.|Выберите провайдера или «Свой» для OpenAI-совместимого API.|प्रदाता चुनें या OpenAI-संगत API के लिए “कस्टम” चुनें।
Use your provider’s base URL or a full /chat/completions or /responses URL. Settings save automatically.|Bruk leverandørens baseadresse eller en full /chat/completions- eller /responses-adresse. Lagres automatisk.|Użyj adresu bazowego lub pełnego adresu /chat/completions albo /responses. Ustawienia zapisują się automatycznie.|Basis-URL oder vollständige /chat/completions- bzw. /responses-URL verwenden. Automatische Speicherung.|Gamitin ang base URL o buong /chat/completions o /responses URL. Awtomatikong sine-save.|Utilisez l’URL de base ou une URL complète /chat/completions ou /responses. Enregistrement automatique.|Usa la URL base o una URL completa /chat/completions o /responses. Se guarda automáticamente.|Bruk baseadressa eller ei full /chat/completions- eller /responses-adresse. Vert lagra automatisk.|Укажите базовый URL или полный URL /chat/completions либо /responses. Автосохранение.|बेस URL या पूरा /chat/completions या /responses URL डालें। सेटिंग्स अपने आप सहेजी जाती हैं।
Use a vision-capable model for photo analysis.|Bruk en modell med bildestøtte for bildeanalyse.|Do zdjęć użyj modelu obsługującego obrazy.|Für Fotos ein bildfähiges Modell verwenden.|Gumamit ng modelong nakakabasa ng larawan.|Utilisez un modèle capable d’analyser les images.|Usa un modelo compatible con imágenes.|Bruk ein modell med biletstøtte for biletanalyse.|Для фото используйте модель с поддержкой изображений.|तस्वीरों के विश्लेषण के लिए विज़न मॉडल इस्तेमाल करें।
Stored in this browser (localStorage). Requests use your key only for the chosen endpoint, directly or through your local relay.|Lagres i nettleseren (localStorage). Nøkkelen brukes kun til valgt endepunkt, direkte eller via lokal videresending.|Zapisany w przeglądarce (localStorage). Klucz jest używany tylko do wybranego endpointu, bezpośrednio lub przez lokalny przekaźnik.|Im Browser gespeichert (localStorage). Der Schlüssel wird nur für den gewählten Endpunkt verwendet.|Naka-save sa browser (localStorage). Sa napiling endpoint lang ginagamit ang key.|Stockée dans le navigateur (localStorage). La clé est utilisée uniquement pour le point choisi.|Guardada en el navegador (localStorage). Solo se usa para el destino elegido.|Vert lagra i nettlesaren (localStorage). Nøkkelen vert berre brukt til valt endepunkt.|Хранится в браузере (localStorage). Ключ используется только для выбранного провайдера.|ब्राउज़र में सहेजी जाती है (localStorage)। कुंजी केवल चुने एंडपॉइंट के लिए इस्तेमाल होती है।
How the key is attached to each request.|Hvordan nøkkelen legges ved hver forespørsel.|Jak klucz jest dołączany do żądania.|Wie der Schlüssel an Anfragen angehängt wird.|Paano ikinakabit ang key sa bawat request.|Comment la clé est jointe aux demandes.|Cómo se añade la clave a cada solicitud.|Korleis nøkkelen vert lagd ved kvar førespurnad.|Как ключ добавляется к запросу.|हर अनुरोध में कुंजी कैसे जोड़ी जाती है।
Extra headers|Ekstra headere|Dodatkowe nagłówki|Zusätzliche Header|Karagdagang headers|En-têtes supplémentaires|Cabeceras adicionales|Ekstra hovudfelt|Дополнительные заголовки|अतिरिक्त हेडर
One per line,|Én per linje,|Jeden w wierszu,|Einer pro Zeile,|Isa bawat linya,|Un par ligne,|Una por línea,|Eitt per linje,|По одному в строке,|हर पंक्ति में एक,
Temperature —|Temperatur —|Temperatura —|Temperatur —|Temperature —|Température —|Temperatura —|Temperatur —|Температура —|तापमान —
Lower is more consistent. 0–0.4 is best for nutrition data.|Lavere gir jevnere svar. 0–0,4 anbefales for næringsdata.|Niższa wartość daje spójniejsze odpowiedzi. Dla żywienia zalecane 0–0,4.|Niedriger ist konsistenter. Für Nährwerte sind 0–0,4 am besten.|Mas mababa, mas pare-pareho. 0–0.4 ang mainam sa nutrisyon.|Plus bas = plus cohérent. 0–0,4 convient aux données nutritionnelles.|Más bajo es más coherente. Para nutrición se recomienda 0–0,4.|Lågare gjev jamnare svar. 0–0,4 er tilrådd for næringsdata.|Ниже — стабильнее. Для питания рекомендуется 0–0,4.|कम मान अधिक सुसंगत है। पोषण डेटा के लिए 0–0.4 बेहतर है।
Max response tokens|Maks svartokens|Maksymalna liczba tokenów odpowiedzi|Maximale Antworttokens|Pinakamaraming response tokens|Tokens de réponse maximaux|Máximo de tokens de respuesta|Maks svartoken|Максимум токенов ответа|अधिकतम जवाब टोकन
Connection test|Tilkoblingstest|Test połączenia|Verbindungstest|Pagsubok ng koneksyon|Test de connexion|Prueba de conexión|Tilkoplingstest|Проверка подключения|कनेक्शन परीक्षण
Sends one tiny request to confirm the endpoint, key and model all work.|Sender en liten forespørsel for å teste endepunkt, nøkkel og modell.|Wysyła małe żądanie, aby sprawdzić endpoint, klucz i model.|Sendet eine kleine Anfrage zum Testen von Endpunkt, Schlüssel und Modell.|Nagpapadala ng maliit na request upang subukan ang endpoint, key at modelo.|Envoie une petite demande pour tester le point, la clé et le modèle.|Envía una pequeña solicitud para comprobar el destino, la clave y el modelo.|Sender ein liten førespurnad for å teste endepunkt, nøkkel og modell.|Отправляет небольшой запрос для проверки провайдера, ключа и модели.|एंडपॉइंट, कुंजी और मॉडल जांचने के लिए छोटा अनुरोध भेजता है।
Demo mode|Demomodus|Tryb demo|Demomodus|Demo mode|Mode démo|Modo demo|Demomodus|Демо-режим|डेमो मोड
Only sample data. Does not analyse photos or use your API.|Kun eksempeldata. Analyserer ikke bilder eller bruker API-en din.|Tylko przykłady. Nie analizuje zdjęć ani nie używa API.|Nur Beispieldaten. Keine Fotoanalyse oder API-Nutzung.|Halimbawang data lang. Hindi sinusuri ang larawan o ginagamit ang API.|Exemples uniquement. N’analyse pas les photos et n’utilise pas votre API.|Solo ejemplos. No analiza fotos ni usa tu API.|Berre dømedata. Analyserer ikkje bilete eller brukar API-en din.|Только примеры. Не анализирует фото и не использует API.|केवल नमूना डेटा। तस्वीरें नहीं जांचता और आपका API इस्तेमाल नहीं करता।
Analyse immediately|Analyser umiddelbart|Analizuj od razu|Sofort analysieren|Suriin agad|Analyser immédiatement|Analizar inmediatamente|Analyser straks|Анализировать сразу|तुरंत विश्लेषण करें
Run as soon as a photo is attached.|Kjør når et bilde legges ved.|Uruchom po dodaniu zdjęcia.|Sobald ein Foto hinzugefügt wird starten.|Suriin pagkakabit ng larawan.|Démarrer dès qu’une photo est jointe.|Iniciar al adjuntar una foto.|Køyr når eit bilete vert lagt ved.|Запускать после добавления фото.|तस्वीर जुड़ते ही शुरू करें।
Compress photos|Komprimer bilder|Kompresuj zdjęcia|Fotos komprimieren|I-compress ang larawan|Compresser les photos|Comprimir fotos|Komprimer bilete|Сжимать фото|तस्वीरें संपीड़ित करें
Downscale to 1280 px before uploading — faster and cheaper.|Reduser til 1280 px før opplasting – raskere og billigere.|Zmniejsz do 1280 px przed wysłaniem — szybciej i taniej.|Vor dem Upload auf 1280 px verkleinern – schneller und günstiger.|Gawing 1280 px bago i-upload — mas mabilis at mura.|Réduire à 1280 px avant l’envoi — plus rapide et moins cher.|Reducir a 1280 px antes de subir — más rápido y barato.|Reduser til 1280 px før opplasting – raskare og billegare.|Уменьшать до 1280 пикселей — быстрее и дешевле.|अपलोड से पहले 1280 px करें — तेज़ और सस्ता।
Structured JSON mode|Strukturert JSON-modus|Tryb struktury JSON|Strukturierter JSON-Modus|Structured JSON mode|Mode JSON structuré|Modo JSON estructurado|Strukturert JSON-modus|Структурированный JSON|संरचित JSON मोड
Ask the model to force JSON output where supported.|Be modellen bruke JSON der det støttes.|Wymuś JSON, jeśli model to obsługuje.|JSON-Ausgabe anfordern, sofern unterstützt.|Hilingin ang JSON kapag suportado.|Demander une sortie JSON si possible.|Pedir salida JSON cuando sea compatible.|Be modellen bruke JSON der det er støtta.|Запрашивать JSON, если поддерживается.|समर्थन होने पर JSON जवाब मांगें।
Result sections|Resultatseksjoner|Sekcje wyników|Ergebnisbereiche|Mga seksyon ng resulta|Sections des résultats|Secciones de resultados|Resultatseksjonar|Разделы результатов|परिणाम अनुभाग
Vitamins and minerals grid.|Oversikt over vitaminer og mineraler.|Tabela witamin i minerałów.|Übersicht zu Vitaminen und Mineralstoffen.|Talaan ng bitamina at mineral.|Tableau des vitamines et minéraux.|Tabla de vitaminas y minerales.|Oversikt over vitamin og mineral.|Таблица витаминов и минералов.|विटामिन और खनिज की तालिका।
Item breakdown|Matvarefordeling|Podział składników|Zutatenübersicht|Detalye ng pagkain|Détail des aliments|Desglose de alimentos|Matvarefordeling|Состав по продуктам|खाद्य विवरण
Per-component table.|Tabell per matvare.|Tabela składników.|Tabelle je Zutat.|Talahanayan bawat sangkap.|Tableau par aliment.|Tabla por componente.|Tabell per matvare.|Таблица по продуктам.|हर घटक की तालिका।
Suggested healthier substitutions.|Forslag til sunnere alternativer.|Propozycje zdrowszych zamienników.|Vorschläge für gesündere Alternativen.|Mungkahing mas masustansiyang kapalit.|Suggestions de substitutions plus saines.|Sugerencias de alternativas más saludables.|Framlegg til sunnare alternativ.|Предложения полезных замен.|स्वस्थ विकल्पों के सुझाव।
Reset settings to defaults|Tilbakestill til standardinnstillinger|Przywróć ustawienia domyślne|Auf Standard zurücksetzen|Ibalik sa default ang settings|Rétablir les paramètres par défaut|Restablecer ajustes predeterminados|Nullstill til standardinnstillingar|Сбросить на стандартные настройки|डिफ़ॉल्ट सेटिंग्स बहाल करें
View full result|Vis hele resultatet|Zobacz pełny wynik|Vollständiges Ergebnis ansehen|Tingnan ang buong resulta|Voir le résultat complet|Ver resultado completo|Vis heile resultatet|Посмотреть полный результат|पूरा परिणाम देखें
Select to analyse in detail|Velg for detaljert analyse|Wybierz do szczegółowej analizy|Für Detailanalyse auswählen|Piliin para suriin nang detalyado|Choisir pour une analyse détaillée|Elegir para analizar en detalle|Vel for detaljert analyse|Выбрать для подробного анализа|विस्तृत विश्लेषण के लिए चुनें
Saved result|Lagret resultat|Zapisany wynik|Gespeichertes Ergebnis|Naka-save na resulta|Résultat enregistré|Resultado guardado|Lagra resultat|Сохранённый результат|सहेजा परिणाम
Imported history|Importert historikk|Zaimportowana historia|Importierter Verlauf|Na-import na history|Historique importé|Historial importado|Importert historikk|Импортированная история|आयात किया इतिहास
No meals match your search.|Ingen måltider passer søket.|Brak posiłków pasujących do wyszukiwania.|Keine passenden Mahlzeiten.|Walang tumugmang pagkain.|Aucun repas ne correspond.|No hay comidas que coincidan.|Ingen måltid passar søket.|Ничего не найдено.|कोई भोजन मेल नहीं खाता।
saved analyses|lagrede analyser|zapisanych analiz|gespeicherte Analysen|naka-save na pagsusuri|analyses enregistrées|análisis guardados|lagra analysar|сохранённых анализов|सहेजे विश्लेषण
diary entries|dagbokoppføringer|wpisów w dzienniku|Tagebucheinträge|tala sa diary|entrées du journal|entradas del diario|dagbokoppføringar|записей дневника|डायरी प्रविष्टियां
kcal from macros|kcal fra makroer|kcal z makroskładników|kcal aus Makros|kcal mula sa macros|kcal des macros|kcal de macros|kcal frå makroar|ккал из макронутриентов|मैक्रो से kcal
of macro energy|av makroenergien|energii z makroskładników|der Makroenergie|ng enerhiya ng macros|de l’énergie des macros|de energía de macros|av makroenergien|энергии макронутриентов|मैक्रो ऊर्जा का
Nutritional quality|Næringskvalitet|Jakość odżywcza|Ernährungsqualität|Kalidad ng nutrisyon|Qualité nutritionnelle|Calidad nutricional|Næringskvalitet|Качество питания|पोषण गुणवत्ता
Excellent|Utmerket|Doskonała|Ausgezeichnet|Napakahusay|Excellente|Excelente|Framifrå|Отличное|उत्कृष्ट
Good|God|Dobra|Gut|Mabuti|Bonne|Buena|God|Хорошее|अच्छा
Moderate|Middels|Umiarkowana|Mittel|Katamtaman|Modérée|Moderada|Middels|Среднее|मध्यम
Poor|Lav|Niska|Gering|Mahina|Faible|Baja|Låg|Низкое|कम
Calcium|Kalsium|Wapń|Kalzium|Calcium|Calcium|Calcio|Kalsium|Кальций|कैल्शियम
Iron|Jern|Żelazo|Eisen|Iron|Fer|Hierro|Jern|Железо|आयरन
Magnesium|Magnesium|Magnez|Magnesium|Magnesium|Magnésium|Magnesio|Magnesium|Магний|मैग्नीशियम
Potassium|Kalium|Potas|Kalium|Potassium|Potassium|Potasio|Kalium|Калий|पोटैशियम
Zinc|Sink|Cynk|Zink|Zinc|Zinc|Zinc|Sink|Цинк|ज़िंक
Folate|Folat|Foliany|Folat|Folate|Folates|Folato|Folat|Фолат|फ़ोलेट
Saturated fat|Mettet fett|Tłuszcze nasycone|Gesättigte Fettsäuren|Saturated fat|Graisses saturées|Grasa saturada|Metta feitt|Насыщенные жиры|संतृप्त वसा
Cholesterol|Kolesterol|Cholesterol|Cholesterin|Cholesterol|Cholestérol|Colesterol|Kolesterol|Холестерин|कोलेस्ट्रॉल
Vitamin A|Vitamin A|Witamina A|Vitamin A|Bitamina A|Vitamine A|Vitamina A|Vitamin A|Витамин A|विटामिन A
Vitamin C|Vitamin C|Witamina C|Vitamin C|Bitamina C|Vitamine C|Vitamina C|Vitamin C|Витамин C|विटामिन C
Vitamin D|Vitamin D|Witamina D|Vitamin D|Bitamina D|Vitamine D|Vitamina D|Vitamin D|Витамин D|विटामिन D
Vitamin B12|Vitamin B12|Witamina B12|Vitamin B12|Bitamina B12|Vitamine B12|Vitamina B12|Vitamin B12|Витамин B12|विटामिन B12
`;
for(const line of moreRows.trim().split('\n')){
  const [english,...values]=line.split('|');if(values.length!==codes.length)throw new Error('Incomplete translation: '+english);
  codes.forEach((code,index)=>TRANSLATIONS[code][english]=values[index]);
}
const finalRows=`
e.g. Oatmeal and a banana|f.eks. havregrøt og en banan|np. owsianka i banan|z. B. Haferbrei und eine Banane|hal. oatmeal at saging|par ex. porridge et banane|p. ej. avena y un plátano|t.d. havregraut og ein banan|например овсянка и банан|जैसे दलिया और केला
Include quantities for better estimates, e.g. “2 eggs and 1 slice of toast”. Blank calories use your configured AI when you press Add entry.|Oppgi mengder, f.eks. «2 egg og 1 brødskive». Tomt kalorifelt bruker AI når du trykker Legg til oppføring.|Podaj ilości, np. „2 jajka i 1 tost”. Puste kalorie używają AI po naciśnięciu Dodaj wpis.|Mengen angeben, z. B. „2 Eier und 1 Toast“. Bei leeren Kalorien nutzt Eintrag hinzufügen die KI.|Ilagay ang dami, hal. “2 itlog at 1 toast”. Gagamitin ang AI kung blangko ang calories kapag nagdagdag ng tala.|Indiquez les quantités, par ex. « 2 œufs et 1 toast ». Les calories vides utilisent l’IA lors de l’ajout.|Indica cantidades, p. ej. «2 huevos y 1 tostada». Las calorías vacías usan IA al añadir la entrada.|Oppgje mengder, t.d. «2 egg og 1 brødskive». Tomt kalorifelt brukar KI når du trykkjer Legg til oppføring.|Укажите количество, например «2 яйца и тост». Если калории пусты, при добавлении используется ИИ.|मात्रा बताएं, जैसे “2 अंडे और 1 टोस्ट”। कैलोरी खाली होने पर प्रविष्टि जोड़ते समय AI इस्तेमाल होता है।
Saved on this device. Only food descriptions needing an AI estimate are sent to your provider.|Lagres på denne enheten. Kun matbeskrivelser som trenger AI-estimat sendes til leverandøren.|Zapisane na urządzeniu. Do dostawcy wysyłane są tylko opisy wymagające szacowania AI.|Auf diesem Gerät gespeichert. Nur Beschreibungen für KI-Schätzungen gehen an den Anbieter.|Naka-save sa device. Mga paglalarawang kailangan ng AI lang ang ipinapadala.|Enregistré sur cet appareil. Seules les descriptions nécessitant l’IA sont envoyées au fournisseur.|Guardado en este dispositivo. Solo se envían descripciones que necesitan IA.|Vert lagra på denne eininga. Berre matskildringar som treng KI-estimat vert sende til leverandøren.|Сохранено на устройстве. Провайдеру отправляются только описания для оценки ИИ.|इस डिवाइस पर सहेजा जाता है। केवल AI अनुमान वाले विवरण प्रदाता को भेजे जाते हैं।
Enter a food and leave calories blank for an AI estimate, add a calorie-only amount, or log an analysed meal.|Legg inn mat med tomt kalorifelt for et AI-estimat, skriv inn kalorier eller logg et analysert måltid.|Wpisz posiłek bez kalorii dla AI, podaj same kalorie lub zapisz przeanalizowany posiłek.|Essen ohne Kalorien für KI eingeben, nur Kalorien hinzufügen oder analysiertes Essen erfassen.|Maglagay ng pagkain na walang calories para sa AI, idagdag lang ang calories, o itala ang nasuring pagkain.|Saisissez un aliment sans calories pour l’IA, ajoutez des calories seules ou un repas analysé.|Introduce comida sin calorías para IA, añade solo calorías o registra una comida analizada.|Legg inn mat med tomt kalorifelt for eit KI-estimat, skriv inn kaloriar eller logg eit analysert måltid.|Введите еду без калорий для ИИ, укажите только калории или запишите анализ.|AI के लिए कैलोरी खाली छोड़कर भोजन भरें, केवल कैलोरी जोड़ें या विश्लेषित भोजन दर्ज करें।
The local relay forwards your key and food only to your configured endpoint. It does not log or store them. Static hosting requires Direct mode.|Lokal videresending sender nøkkel og mat kun til valgt endepunkt, uten lagring. Statisk hosting krever Direkte-modus.|Lokalny przekaźnik wysyła klucz i jedzenie tylko do wybranego endpointu, bez zapisu. Hosting statyczny wymaga trybu bezpośredniego.|Der Relay sendet Schlüssel und Essen nur an den gewählten Endpunkt, ohne Speicherung. Statisches Hosting erfordert Direktmodus.|Sa napiling endpoint lang ipinapadala ng relay ang key at pagkain, walang sine-save. Kailangan ang Direct mode sa static hosting.|Le relais envoie la clé et l’aliment uniquement au point choisi, sans stockage. L’hébergement statique nécessite le mode Direct.|El relay envía clave y comida solo al destino elegido, sin guardarlas. El alojamiento estático requiere modo Directo.|Lokal vidaresending sender nøkkel og mat berre til valt endepunkt, utan lagring. Statisk hosting krev Direkte-modus.|Ретранслятор передаёт ключ и еду только выбранному провайдеру, без сохранения. Для статического хостинга нужен прямой режим.|रिले कुंजी और भोजन केवल चुने एंडपॉइंट को भेजता है, बिना सहेजे। स्थिर होस्टिंग के लिए डायरेक्ट मोड चाहिए।
Full analyses save automatically to Previous analyses, with no age or entry limit. Browser data stays on this device; use the library backup for long-term safekeeping.|Hele analyser lagres automatisk i Tidligere analyser uten tids- eller antallsgrense. Data blir på enheten; ta sikkerhetskopi for langtidslagring.|Analizy zapisują się automatycznie bez limitu czasu i liczby. Dane pozostają na urządzeniu; twórz kopię zapasową.|Analysen werden automatisch ohne Alters- oder Mengenlimit gespeichert. Daten bleiben auf dem Gerät; sichere sie per Backup.|Awtomatikong sine-save ang pagsusuri nang walang limitasyon. Nasa device ang data; gumawa ng backup para sa pangmatagalang pag-iingat.|Les analyses sont enregistrées automatiquement sans limite. Les données restent sur l’appareil ; gardez une sauvegarde.|Los análisis se guardan automáticamente sin límites. Los datos quedan en el dispositivo; conserva una copia de seguridad.|Heile analysar vert lagra automatisk utan tids- eller talgrense. Data vert på eininga; ta tryggleikskopi for langtidslagring.|Анализы сохраняются автоматически без ограничений. Данные остаются на устройстве; делайте резервные копии.|पूरे विश्लेषण बिना सीमा अपने आप सहेजे जाते हैं। डेटा इसी डिवाइस पर रहता है; लंबे समय के लिए बैकअप रखें।
Calculated using 4 / 4 / 9 kcal per gram; may differ from total calories because of fibre and rounding.|Beregnet med 4 / 4 / 9 kcal per gram; fiber og avrunding kan gi avvik fra totale kalorier.|Obliczono według 4 / 4 / 9 kcal na gram; błonnik i zaokrąglenia mogą zmienić sumę.|Mit 4 / 4 / 9 kcal pro Gramm berechnet; Ballaststoffe und Rundungen können Abweichungen verursachen.|Kinuwenta gamit ang 4 / 4 / 9 kcal bawat gramo; maaaring mag-iba dahil sa hibla at rounding.|Calculé avec 4 / 4 / 9 kcal par gramme ; fibres et arrondis peuvent modifier le total.|Calculado con 4 / 4 / 9 kcal por gramo; fibra y redondeo pueden cambiar el total.|Rekna med 4 / 4 / 9 kcal per gram; fiber og avrunding kan gje avvik frå samla kaloriar.|Рассчитано по 4 / 4 / 9 ккал на грамм; клетчатка и округление могут изменить итог.|4 / 4 / 9 kcal प्रति ग्राम से गणना; फ़ाइबर और राउंडिंग से कुल बदल सकता है।
total estimated energy for the portion|estimert energi for hele porsjonen|szacowana energia całej porcji|geschätzte Gesamtenergie der Portion|tinatayang enerhiya ng buong dami|énergie totale estimée de la portion|energía total estimada de la porción|estimert energi for heile porsjonen|оценка энергии всей порции|मात्रा की अनुमानित कुल ऊर्जा
Close settings|Lukk innstillinger|Zamknij ustawienia|Einstellungen schließen|Isara ang settings|Fermer les paramètres|Cerrar ajustes|Lukk innstillingar|Закрыть настройки|सेटिंग्स बंद करें
Close meal library|Lukk måltidsbibliotek|Zamknij bibliotekę|Mahlzeitenbibliothek schließen|Isara ang talaan|Fermer la bibliothèque|Cerrar biblioteca|Lukk måltidsbibliotek|Закрыть библиотеку|लाइब्रेरी बंद करें
Toggle theme|Bytt tema|Zmień motyw|Design wechseln|Palitan ang tema|Changer de thème|Cambiar tema|Byt tema|Сменить тему|थीम बदलें
Voice input|Taleinndata|Wprowadzanie głosem|Spracheingabe|Voice input|Saisie vocale|Entrada por voz|Taleinndata|Голосовой ввод|आवाज़ से इनपुट
Describe food by voice|Beskriv mat med stemmen|Opisz jedzenie głosem|Essen per Sprache beschreiben|Ilarawan ang pagkain sa boses|Décrire l’aliment à voix haute|Describir comida por voz|Skildre mat med røysta|Описать еду голосом|आवाज़ से भोजन बताएं
Edit|Rediger|Edytuj|Bearbeiten|I-edit|Modifier|Editar|Rediger|Изменить|संपादित करें
Delete|Slett|Usuń|Löschen|Burahin|Supprimer|Eliminar|Slett|Удалить|मिटाएं
Edit entry|Rediger oppføring|Edytuj wpis|Eintrag bearbeiten|I-edit ang tala|Modifier l’entrée|Editar entrada|Rediger oppføring|Изменить запись|प्रविष्टि संपादित करें
Delete entry|Slett oppføring|Usuń wpis|Eintrag löschen|Burahin ang tala|Supprimer l’entrée|Eliminar entrada|Slett oppføring|Удалить запись|प्रविष्टि मिटाएं
Available models|Tilgjengelige modeller|Dostępne modele|Verfügbare Modelle|Mga modelong available|Modèles disponibles|Modelos disponibles|Tilgjengelege modellar|Доступные модели|उपलब्ध मॉडल
Fetch models or enter your exact model ID|Hent modeller eller skriv inn modellens ID|Pobierz modele lub wpisz identyfikator|Modelle abrufen oder Modell-ID eingeben|Kunin ang modelo o ilagay ang ID|Chargez les modèles ou saisissez l’ID|Obtén modelos o escribe el ID exacto|Hent modellar eller skriv inn modell-ID|Загрузите модели или введите ID|मॉडल लाएं या सही मॉडल ID डालें
Custom endpoint|Egendefinert endepunkt|Niestandardowy endpoint|Eigener Endpunkt|Custom endpoint|Point personnalisé|Destino personalizado|Eigendefinert endepunkt|Свой адрес API|कस्टम एंडपॉइंट
Local relay — avoids browser CORS blocks|Lokal videresending – unngår CORS-blokkering|Lokalny przekaźnik — omija blokady CORS|Lokaler Relay – vermeidet CORS-Sperren|Lokal na relay — iwas CORS block|Relais local — évite les blocages CORS|Relay local — evita bloqueos CORS|Lokal vidaresending – unngår CORS-blokkering|Локальный ретранслятор — без блокировок CORS|स्थानीय रिले — CORS अवरोध से बचाता है
Direct browser requests|Direkte nettleserforespørsler|Bezpośrednie żądania z przeglądarki|Direkte Browseranfragen|Direktang request sa browser|Demandes directes du navigateur|Solicitudes directas del navegador|Direkte nettlesarførespurnader|Прямые запросы из браузера|सीधे ब्राउज़र अनुरोध
Auto — Chat Completions, then Responses if required|Auto – Chat Completions, deretter Responses ved behov|Auto — Chat Completions, potem Responses w razie potrzeby|Auto – Chat Completions, dann bei Bedarf Responses|Auto — Chat Completions, tapos Responses kung kailangan|Auto — Chat Completions, puis Responses si nécessaire|Auto — Chat Completions, luego Responses si hace falta|Auto – Chat Completions, så Responses ved behov|Авто — Chat Completions, затем Responses при необходимости|ऑटो — Chat Completions, फिर आवश्यकता पर Responses
View a full saved result without using AI, or prepare a new analysis. Originals are never replaced.|Se et lagret resultat uten AI eller forbered en ny analyse. Originalen beholdes.|Zobacz wynik bez AI lub przygotuj nową analizę. Oryginały pozostają.|Gespeichertes Ergebnis ohne KI ansehen oder neue Analyse vorbereiten. Originale bleiben erhalten.|Tingnan ang resulta nang walang AI o maghanda ng bagong pagsusuri. Hindi pinapalitan ang orihinal.|Voir un résultat sans IA ou préparer une analyse. Les originaux sont conservés.|Ver un resultado sin IA o preparar un análisis. Se conservan los originales.|Sjå eit lagra resultat utan KI eller førebu ein ny analyse. Originalen vert teken vare på.|Посмотрите результат без ИИ или подготовьте новый анализ. Оригиналы сохраняются.|बिना AI सहेजा परिणाम देखें या नया विश्लेषण तैयार करें। मूल परिणाम बने रहते हैं।
Choose a logged food to load its description into Analyse Food. Your diary entry will not change.|Velg logget mat for å åpne beskrivelsen i Analyser mat. Dagbokoppføringen endres ikke.|Wybierz posiłek do analizy. Wpis w dzienniku nie zmieni się.|Erfasstes Essen zur Analyse wählen. Der Tagebucheintrag bleibt unverändert.|Pumili ng pagkain para sa pagsusuri. Hindi mababago ang tala.|Choisissez un aliment enregistré à analyser. L’entrée reste inchangée.|Elige una comida registrada para analizarla. La entrada no cambia.|Vel logga mat for analyse. Dagbokoppføringa vert ikkje endra.|Выберите записанную еду для анализа. Запись не изменится.|विश्लेषण के लिए दर्ज भोजन चुनें। डायरी प्रविष्टि नहीं बदलेगी।
Your full analyses will appear here after you analyse a meal.|Hele analyser vises her etter at du analyserer et måltid.|Analizy pojawią się tutaj po przeanalizowaniu posiłku.|Nach einer Mahlzeitenanalyse erscheinen hier die Ergebnisse.|Dito makikita ang pagsusuri pagkatapos magsuri ng pagkain.|Les analyses apparaîtront ici après l’analyse d’un repas.|Tus análisis aparecerán aquí tras analizar una comida.|Heile analysar vert viste her etter at du analyserer eit måltid.|Здесь появятся результаты анализа еды.|भोजन का विश्लेषण करने के बाद परिणाम यहां दिखेंगे।
No diary meals yet. Log a named food in Daily Food Diary first.|Ingen dagbokmåltider ennå. Logg mat i Daglig matdagbok først.|Brak posiłków. Najpierw dodaj posiłek do dziennika.|Noch keine Mahlzeiten. Erfasse zuerst Essen im Tagebuch.|Wala pang pagkain. Itala muna sa diary.|Aucun repas. Enregistrez d’abord un aliment dans le journal.|Sin comidas aún. Registra primero un alimento en el diario.|Ingen dagbokmåltid enno. Logg mat i matdagboka først.|Нет еды в дневнике. Сначала добавьте продукт.|डायरी में भोजन नहीं है। पहले कोई भोजन दर्ज करें।
Demo estimate — connect a model for real analysis|Demoestimat – koble til en modell for ekte analyse|Szacunek demo — podłącz model do prawdziwej analizy|Demo-Schätzung – Modell für echte Analyse verbinden|Demo estimate — ikonekta ang modelo para sa tunay na pagsusuri|Estimation démo — connectez un modèle|Estimación demo — conecta un modelo|Demoestimat – kopla til ein modell for ekte analyse|Демо-оценка — подключите модель|डेमो अनुमान — असली विश्लेषण के लिए मॉडल जोड़ें
`;
for(const line of finalRows.trim().split('\n')){
  const [english,...values]=line.split('|');if(values.length!==codes.length)throw new Error('Incomplete translation: '+english);
  codes.forEach((code,index)=>TRANSLATIONS[code][english]=values[index]);
}

TRANSLATIONS.ur=URDU_TRANSLATIONS;

// Shared deletion dialog strings (food names remain untranslated).
const deletionRows=`
AI confidence unavailable|AI-sikkerhet er ikke tilgjengelig|Pewność AI niedostępna|KI-Konfidenz nicht verfügbar|Hindi available ang AI confidence|Confiance IA indisponible|Confianza de IA no disponible|KI-tryggleik er ikkje tilgjengeleg|Уверенность ИИ недоступна|AI का विश्वास स्तर उपलब्ध नहीं|AI کا اعتماد دستیاب نہیں
saved analysis|lagret analyse|zapisana analiza|gespeicherte Analyse|naka-save na pagsusuri|analyse enregistrée|análisis guardado|lagra analyse|сохранённый анализ|सहेजा विश्लेषण|محفوظ تجزیہ
diary entry|dagbokoppføring|wpis w dzienniku|Tagebucheintrag|tala sa diary|entrée du journal|entrada del diario|dagbokoppføring|запись дневника|डायरी प्रविष्टि|ڈائری کا اندراج
Delete saved analysis?|Slette lagret analyse?|Usunąć zapisaną analizę?|Gespeicherte Analyse löschen?|Burahin ang naka-save na pagsusuri?|Supprimer l’analyse enregistrée ?|¿Eliminar el análisis guardado?|Slette lagra analyse?|Удалить сохранённый анализ?|सहेजा विश्लेषण मिटाएं?|محفوظ تجزیہ حذف کریں؟
Delete diary meal?|Slette dagbokmåltid?|Usunąć posiłek z dziennika?|Tagebuchmahlzeit löschen?|Burahin ang pagkain sa diary?|Supprimer le repas du journal ?|¿Eliminar la comida del diario?|Slette dagbokmåltid?|Удалить еду из дневника?|डायरी का भोजन मिटाएं?|ڈائری کا کھانا حذف کریں؟
Delete all analyses?|Slette alle analyser?|Usunąć wszystkie analizy?|Alle Analysen löschen?|Burahin lahat ng pagsusuri?|Supprimer toutes les analyses ?|¿Eliminar todos los análisis?|Slette alle analysar?|Удалить все анализы?|सभी विश्लेषण मिटाएं?|تمام تجزیے حذف کریں؟
Delete all diary meals?|Slette alle dagbokmåltider?|Usunąć wszystkie posiłki z dziennika?|Alle Tagebuchmahlzeiten löschen?|Burahin lahat ng pagkain sa diary?|Supprimer tous les repas du journal ?|¿Eliminar todas las comidas del diario?|Slette alle dagbokmåltid?|Удалить всю еду из дневника?|डायरी के सभी भोजन मिटाएं?|ڈائری کے تمام کھانے حذف کریں؟
Clear this day?|Tømme denne dagen?|Wyczyścić ten dzień?|Diesen Tag leeren?|Burahin ang araw na ito?|Effacer cette journée ?|¿Borrar este día?|Tømme denne dagen?|Очистить этот день?|इस दिन को साफ़ करें?|یہ دن صاف کریں؟
Delete analysis|Slett analyse|Usuń analizę|Analyse löschen|Burahin ang pagsusuri|Supprimer l’analyse|Eliminar análisis|Slett analyse|Удалить анализ|विश्लेषण मिटाएं|تجزیہ حذف کریں
Delete meal|Slett måltid|Usuń posiłek|Mahlzeit löschen|Burahin ang pagkain|Supprimer le repas|Eliminar comida|Slett måltid|Удалить еду|भोजन मिटाएं|کھانا حذف کریں
This cannot be undone.|Dette kan ikke angres.|Tej operacji nie można cofnąć.|Dies kann nicht rückgängig gemacht werden.|Hindi na ito maibabalik.|Cette action est irréversible.|Esta acción no se puede deshacer.|Dette kan ikkje angrast.|Это действие нельзя отменить.|इसे पूर्ववत नहीं किया जा सकता।|اس عمل کو واپس نہیں کیا جا سکتا۔
Other analyses and diary entries will be kept.|Andre analyser og dagbokoppføringer beholdes.|Inne analizy i wpisy w dzienniku zostaną zachowane.|Andere Analysen und Tagebucheinträge bleiben erhalten.|Mananatili ang ibang pagsusuri at mga tala sa diary.|Les autres analyses et entrées du journal seront conservées.|Se conservarán los demás análisis y entradas del diario.|Andre analysar og dagbokoppføringar vert tekne vare på.|Другие анализы и записи дневника сохранятся.|अन्य विश्लेषण और डायरी प्रविष्टियां बनी रहेंगी।|دیگر تجزیے اور ڈائری کے اندراجات محفوظ رہیں گے۔
This meal will be removed from your diary and the daily calorie total will be updated. Your saved analyses will be kept.|Måltidet fjernes fra dagboken og dagens kaloritotal oppdateres. Lagrede analyser beholdes.|Posiłek zostanie usunięty z dziennika, a dzienna suma kalorii zostanie zaktualizowana. Zapisane analizy zostaną zachowane.|Diese Mahlzeit wird aus dem Tagebuch entfernt und die tägliche Kaloriensumme aktualisiert. Gespeicherte Analysen bleiben erhalten.|Aalisin ang pagkain sa diary at ia-update ang kabuuang calorie sa araw. Mananatili ang mga naka-save na pagsusuri.|Ce repas sera retiré du journal et le total calorique quotidien sera actualisé. Vos analyses enregistrées seront conservées.|Se eliminará esta comida del diario y se actualizará el total diario de calorías. Se conservarán tus análisis guardados.|Måltidet vert fjerna frå dagboka og kalorisummen for dagen vert oppdatert. Lagra analysar vert tekne vare på.|Эта еда будет удалена из дневника, а дневная сумма калорий обновится. Сохранённые анализы останутся.|यह भोजन डायरी से हट जाएगा और दिन की कुल कैलोरी अपडेट होगी। सहेजे विश्लेषण बने रहेंगे।|یہ کھانا ڈائری سے ہٹا دیا جائے گا اور دن کی کل کیلوریز اپ ڈیٹ ہو جائیں گی۔ محفوظ تجزیے برقرار رہیں گے۔
All meals for this day will be deleted and its calorie total will reset. Other days and saved analyses will be kept.|Alle måltider for denne dagen slettes og kaloritotalen nullstilles. Andre dager og lagrede analyser beholdes.|Wszystkie posiłki z tego dnia zostaną usunięte, a suma kalorii wyzerowana. Inne dni i zapisane analizy zostaną zachowane.|Alle Mahlzeiten dieses Tages werden gelöscht und die Kaloriensumme zurückgesetzt. Andere Tage und gespeicherte Analysen bleiben erhalten.|Buburahin lahat ng pagkain sa araw na ito at magre-reset ang kabuuang calorie. Mananatili ang ibang araw at naka-save na pagsusuri.|Tous les repas de cette journée seront supprimés et le total calorique sera remis à zéro. Les autres jours et analyses enregistrées seront conservés.|Se eliminarán todas las comidas de este día y su total de calorías se pondrá a cero. Se conservarán los demás días y análisis guardados.|Alle måltid for denne dagen vert sletta og kalorisummen nullstilt. Andre dagar og lagra analysar vert tekne vare på.|Вся еда за этот день будет удалена, а сумма калорий обнулится. Другие дни и сохранённые анализы останутся.|इस दिन के सभी भोजन मिट जाएंगे और कुल कैलोरी शून्य हो जाएगी। अन्य दिन और सहेजे विश्लेषण बने रहेंगे।|اس دن کے تمام کھانے حذف ہو جائیں گے اور کل کیلوریز صفر ہو جائیں گی۔ دوسرے دن اور محفوظ تجزیے برقرار رہیں گے۔
Every saved analysis will be deleted, including those outside your search. Diary meals and daily calorie totals will be kept. Download a history backup first if needed.|Alle lagrede analyser slettes, også de utenfor søket ditt. Dagbokmåltider og daglige kaloritotaler beholdes. Last ned en historikksikkerhetskopi først ved behov.|Każda zapisana analiza zostanie usunięta, także spoza wyników wyszukiwania. Posiłki z dziennika i dzienne sumy kalorii zostaną zachowane. W razie potrzeby najpierw pobierz kopię historii.|Jede gespeicherte Analyse wird gelöscht, auch außerhalb der Suche. Tagebuchmahlzeiten und tägliche Kaloriensummen bleiben erhalten. Bei Bedarf zuerst eine Verlaufssicherung herunterladen.|Buburahin lahat ng naka-save na pagsusuri, pati ang wala sa iyong paghahanap. Mananatili ang pagkain sa diary at arawang kabuuang calorie. Mag-download muna ng backup ng history kung kailangan.|Toutes les analyses enregistrées seront supprimées, même hors des résultats de recherche. Les repas du journal et les totaux caloriques quotidiens seront conservés. Téléchargez d’abord une sauvegarde de l’historique si nécessaire.|Se eliminarán todos los análisis guardados, incluidos los que no aparecen en tu búsqueda. Se conservarán las comidas del diario y los totales diarios de calorías. Descarga primero una copia del historial si la necesitas.|Alle lagra analysar vert sletta, også dei utanfor søket ditt. Dagbokmåltid og daglege kalorisummar vert tekne vare på. Last ned ein tryggleikskopi av historikken først ved behov.|Все сохранённые анализы будут удалены, включая не найденные поиском. Еда в дневнике и дневные суммы калорий сохранятся. При необходимости сначала скачайте резервную копию истории.|सभी सहेजे विश्लेषण मिट जाएंगे, खोज से बाहर के भी। डायरी के भोजन और दिन की कुल कैलोरी बनी रहेगी। ज़रूरत हो तो पहले इतिहास का बैकअप डाउनलोड करें।|تمام محفوظ تجزیے حذف ہو جائیں گے، بشمول تلاش سے باہر کے تجزیے۔ ڈائری کے کھانے اور روزانہ کی کل کیلوریز برقرار رہیں گی۔ ضرورت ہو تو پہلے ہسٹری کا بیک اپ ڈاؤن لوڈ کریں۔
Diary meals from every date will be deleted, including those outside your search. Daily calorie totals will reset. Saved analyses will be kept.|Dagbokmåltider fra alle datoer slettes, også de utenfor søket ditt. Daglige kaloritotaler nullstilles. Lagrede analyser beholdes.|Posiłki z dziennika ze wszystkich dat zostaną usunięte, także spoza wyników wyszukiwania. Dzienne sumy kalorii zostaną wyzerowane. Zapisane analizy zostaną zachowane.|Tagebuchmahlzeiten aller Tage werden gelöscht, auch außerhalb der Suche. Tägliche Kaloriensummen werden zurückgesetzt. Gespeicherte Analysen bleiben erhalten.|Buburahin ang pagkain sa diary sa lahat ng petsa, pati ang wala sa iyong paghahanap. Magre-reset ang arawang kabuuang calorie. Mananatili ang naka-save na pagsusuri.|Les repas du journal de toutes les dates seront supprimés, même hors des résultats de recherche. Les totaux caloriques quotidiens seront remis à zéro. Les analyses enregistrées seront conservées.|Se eliminarán las comidas del diario de todas las fechas, incluidas las que no aparecen en tu búsqueda. Los totales diarios de calorías se pondrán a cero. Se conservarán los análisis guardados.|Dagbokmåltid frå alle datoar vert sletta, også dei utanfor søket ditt. Daglege kalorisummar vert nullstilte. Lagra analysar vert tekne vare på.|Еда в дневнике за все даты будет удалена, включая не найденную поиском. Дневные суммы калорий обнулятся. Сохранённые анализы останутся.|सभी तारीखों के डायरी भोजन मिट जाएंगे, खोज से बाहर के भी। दिन की कुल कैलोरी शून्य हो जाएगी। सहेजे विश्लेषण बने रहेंगे।|تمام تاریخوں کے ڈائری کھانے حذف ہو جائیں گے، بشمول تلاش سے باہر کے کھانے۔ روزانہ کی کل کیلوریز صفر ہو جائیں گی۔ محفوظ تجزیے برقرار رہیں گے۔
`;
for(const line of deletionRows.trim().split('\n')){
  const [english,...values]=line.split('|');
  const languages=[...codes,'ur'];
  if(values.length!==languages.length)throw new Error('Incomplete deletion translation: '+english);
  languages.forEach((code,index)=>TRANSLATIONS[code][english]=values[index]);
}
